### ISSUE TITLE
Allow a single tequila server instance to be run multiple times

### ISSUE THREAD

**Issue by Chunkr-** [Snaipe/Tequila#3]
It would be really handy if a single tequila instance could be ran multiple times, e.g. you want minigame_x to have 33 instances at all time e.g.

[options]
jvm: jvm.opts
application: application.opts
instances: 30

this would come in handy for people running large minecraft servers.

**Comment by jessedev** [comment]
This. Tequila looks awesome, but is only useful for us when we can run the same instance multiple times. If you can do this, chapeau <3

**Comment by Snaipe** [comment]
This is more tricky than it sounds. Starting the server multiple times on the same root could cause damage if the data that goes through them change (mainly plugin data and world regions).
I see two possible solutions:
- Either put the worlds and plugins directory read-only before startup, but this will likely spawn a whole lot of undesired error messages; or,
- Mirror the server to a temporary directory (maybe `/tmp/tequila-\<server name\>-\<instance count\>/`) and discard the directory when the server is explicitly stopped.
  I will probably go for the second solution, and put an optional start parameter to spawn multiple instances (like `tequila start -i 30` to spawn 30 instances).

**Comment by jessedev** [comment]
Temporary directories are the way to go.

**Comment by jessedev** [comment]
By the way, It'd be great if we can use the amount of instances as a variable in the instance configurations. This way, we can assign a port using the jvm opts with "--port 20$i"
So:
Instance 1: Port 2001
Instance 2: Port 2002
etc. etc.

**Comment by Snaipe** [comment]
I started to implement the feature, having new variables is okay, but using the variable count to bind port might cause undesired effects. Instead, I am thinking of adding a port range in the config, and a new instance will have its port chosen withing these boundaries, and specified in a ${port} variable.
The instance number might also be accessed with a variable in the opts file, but I would use it to specify system properties (maybe for plugins to be aware of the instance number), like adding -Dtequila.instance=${instance_count}

**Comment by Chunkr-** [comment]
Sounds good :+1:

**Comment by Snaipe** [comment]
The feature is (partially) implemented on the bleeding branch:
Multiple instances are disabled by default and may be enabled through the configuration file.
There are two kinds of policies with how instances work, (port) **binding policies** and **startup policies**.

**Startup policies** define what should be done before (and after) an instance is run -- currently, there are the two following:
- the `copy` policy will copy the server directory to the (temporary) instance directory, and delete the instance directory after the associated instance stopped.
- the `union` policy will try to mount-union the server directory as a read-only layer to the instance directory. No copy is performed, and changes are discarded after the instance stopped. (Note: this policy can only be performed as root, even though it will start the server as the user specified in the configuration; and it cannot be used with the screen wrapper.)

**Binding policies** define how ports should be associated with the instance.
- the `fixed` policy will associate in the same order, from a lower bound, a port to an instance. This means that if the lower bound is 25565, instance 1 will get port 25565, instance 2 will get port 25566, etc...
- the `dynamic` policy will try to associate the lowest unused port within the defined port range to an instance, regardless of order; this means that if the port range is 25565 to 25665, and we first start instances 1 and 2, instance 1 will get port 25565, and instance 2 will get port 25566 -- but then if we stop instance 1, then start instance 3, then instance 3 will get port 25565.

Everything is implemented except for the dynamic binding policy. There are a few bugs I have to fix (mostly on the daemon wrapper I had to rush to get to test the union policy) and it should be good.

**Comment by Chunkr-** [comment]
:heart: Can't wait to test this, thanks :-)

**Comment by Snaipe** [comment]
The feature is fully implemented, merged on bleeding, and will be included in the upcoming release.
