### ISSUE TITLE
Bleeding - unsure how to start multiple instances.

### ISSUE THREAD

**Issue by Chunkr-** [Snaipe/Tequila#7]
I'm not quite sure how to use multiple instances when booting a server via tequilla

```
root@game01:/home/minecraft/servers# tequila start -n 10 survival
Too many arguments to 'start': ['10', 'survival']
root@game01:/home/minecraft/servers# tequila start survival instances=10
Too many arguments to 'start': ['instances=10']
root@game01:/home/minecraft/servers# tequila start survival -instances 100
Too many arguments to 'start': ['-instances', '100']
root@game01:/home/minecraft/servers# tequila start survival instances:10
Too many arguments to 'start': ['instances:10']
```

**Comment by Snaipe** [comment]
Ah, I didn't document it yet, but I have changed the way to reference to instances. To start the instance n, use `tequila start servername#n`, to start instances n through m, use #n-m.
(I'm still not quite sure about the syntax though, but it should pave the way to reference other things than lone servers.)
